#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        iif "lo" accept
        ct state established,related accept
        tcp dport 22 accept
        ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        ct state established,related accept
        iifname "ens19" oifname "ens18" accept
        iifname "ens19" oifname "ens20" ip daddr 172.16.87.10 tcp dport 7587 accept
        iifname "ens19" oifname "ens20" ip daddr 172.16.87.10 icmp type echo-request accept
        iifname "ens20" oifname "ens19" drop
        iifname "ens20" oifname "ens18" udp dport 53 accept
        iifname "ens20" oifname "ens18" tcp dport 53 accept
        iifname "ens18" oifname "ens20" tcp dport 7587 limit rate 1/minute accept
    }
}

table ip nat {

    chain prerouting {
        type nat hook prerouting priority 0;

        tcp dport 7587 dnat to 172.16.87.10:7587
    }

    chain postrouting {
        type nat hook postrouting priority 100;

        oifname "ens18" masquerade
    }
}
